import unittest

from . import assertPopen


class HelpTest(unittest.TestCase):
    def test_help(self):
        output = assertPopen(['dvci', 'help'])
        self.assertRegex(
            output, r'^usage: dvci \[-h\] \[--version\] COMMAND \.\.\.'
        )

    def test_help_subcommand(self):
        output = assertPopen(['dvci', 'help', 'deploy'])
        self.assertRegex(output, r'^usage: dvci deploy')

    def test_help_subcommand_extra(self):
        output = assertPopen(['dvci', 'help', 'deploy', '--rebase'])
        self.assertRegex(output, r'^usage: dvci deploy')


class GenerateCompletionTest(unittest.TestCase):
    def test_completion(self):
        output = assertPopen(['dvci', 'generate-completion', '-sbash'])
        self.assertRegex(output, r'(?m)^# AUTOMATCALLY GENERATED by `shtab`')
